### ISSUE TITLE
Implement an editing mode for the profile page

### ISSUE THREAD

**Issue by rowantran** [ucsb-cs148-f21/project-t10-animelist#113]
Acceptance criteria:
* [ ] There is some interface element allowing the user to enter an editing mode on their profile page.
* [ ] After entering the editing mode, there is an interface element allowing the user to exit this mode.
* [ ] The add block button implemented in #112 will only be accessible after entering this editing mode.
* [ ] While in this editing mode, the displayed blocks will show placeholders rather than their actual values, e.g. the user list block will display "User List" instead of the actual user list.
* [ ] Apart from adding blocks, the user can also reorder blocks in this mode.
  * [ ] Since each block currently corresponds to a single row, we can just give each row buttons that move it up and down in the blocks array in the state.
* [ ] The user can also edit blocks in this mode. Each block should have an edit button (if it has any inputs) that brings up the same modal from #112, pre-populated with the current configuration, and allows the user to change the values.
* [ ] The user can also delete blocks in this mode. Each block should have a button that deletes it and its row.
* [ ] After exiting the editing mode, the updated list of blocks will be sent to the backend and the list will be reloaded.
* [ ] The updated list of blocks will no longer be sent to the backend immediately after adding a block (undoes changes from #112.)

Notes: originally envisioned this using drag-and-drop, but the amount of additional work required would be large so I don't think it's feasible. instead we can just use buttons to rearrange the rows`
